
version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - main-network

  mongo:
    image: "mongo:4.4.3"
    container_name: mongo
    hostname: mongo
    networks:
      - main-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    ports:
      - 27017:27017
    command: [ "--bind_ip", "0.0.0.0" ]
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
networks:
  main-network:
    driver: bridge